### ISSUE TITLE
`onDrop` called at page load

### ISSUE THREAD

**Issue by DumboJet** [codef0rmer/angular-dragdrop#128]
The `onDrop` method is called when the page loads for every item that has is defined.
This doesn't make sense to me.

An example of using it without arrays and doing ALL handling in event handlers like `onDrop` would be appreciated.

Also, I get this error:

```
 TypeError: Cannot set property 'jqyoui_pos' of undefined
     at angular.module.service.mutateDroppable (http://localhost:2014/Scripts/Angularjs/Libraries/AngularDragDrop/angular-dragdrop.js:179:67)
     at null.<anonymous> (http://localhost:2014/Scripts/Angularjs/Libraries/AngularDragDrop/angular-dragdrop.js:110:18)
     at val (http://localhost:2014/Scripts/angular.js:1049:18)
     at http://localhost:2014/Scripts/angular.js:14158:28
     at completeOutstandingRequest (http://localhost:2014/Scripts/angular.js:4337:10)
     at http://localhost:2014/Scripts/angular.js:4638:7 
```

Probably because I try to use it with empty arrays as model (I want to use only the onDrag event and get information from inside there on what was dragged where. Is this possible?).

UPDATE: Using an empty object for model prevents the above error and the data that I want seem to be inside the arguments. :)

**Comment by ericpeters0n** [comment]
For those that come later, 'placeholder:true' can apparently cause the
```
TypeError: Cannot set property 'jqyoui_pos' of undefined
```
under certain conditions..

**Comment by adeel-raza** [comment]
@ericpeters0n  Thanks a lot that was exactly the case for me.
