### ISSUE TITLE
Unable to initiate Drag and Drop

### ISSUE THREAD

**Issue by saurabh-p** [codef0rmer/angular-dragdrop#164]
TypeError: undefined is not a function
    at t.module.service.directive.link.f (http://localhost:3000/assets/angular/vendors/angular_dragdrop.min.js:1:4374)
    at t.module.service.directive.link (http://localhost:3000/assets/angular/vendors/angular_dragdrop.min.js:1:4450)

**Comment by pumpi** [comment]
same here +1

**Comment by codef0rmer** [comment]
@saurabh-p and @pumpi Make sure you guys have included jquery and jqueryui before angular.js. Share a fiddle or plunkr if possible to better investigate the problem.

**Comment by saurabh-p** [comment]
Ahh, I had been using this module, thinking it being independent of jquery and jqueryui.
