### ISSUE TITLE
I got this error running the sample in README

### ISSUE THREAD

**Issue by verystrongjoe** [codef0rmer/angular-dragdrop#176]
TypeError: r.draggable is not a function
    at f (http://localhost:8501/components/angular-dragdrop/src/angular-dragdrop.min.js:29:4373)
    at link (http://localhost:8501/components/angular-dragdrop/src/angular-dragdrop.min.js:29:4449)
    at nodeLinkFn (http://localhost:8501/components/angular/angular.js:6752:13)
    at compositeLinkFn (http://localhost:8501/components/angular/angular.js:6146:13)
    at nodeLinkFn (http://localhost:8501/components/angular/angular.js:6746:24)
    at compositeLinkFn (http://localhost:8501/components/angular/angular.js:6146:13)
    at publicLinkFn (http://localhost:8501/components/angular/angular.js:6042:30)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1532:22
    at http://localhost:8501/components/angular-ui-router/release/angular-ui-router.js:3905:9
    at nodeLinkFn (http://localhost:8501/components/angular/angular.js:6752:13) <span data-drag="true" jqyoui-draggable="">(anonymous function) @ angular.js:10126
angular.js:10126 TypeError: r.draggable is not a function
    at Object.f [as fn] (angular-dragdrop.min.js:29)
    at Scope.$digest (angular.js:12650)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1468)
    at Scope.$apply (angular.js:12915)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1478)
    at angular.js:1447
    at Object.invoke (angular.js:3965)
    at doBootstrap (angular.js:1445)
    at Object.angular.resumeBootstrap (angular.js:1467)
    at maybeBootstrap (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:535)(anonymous function) @ angular.js:10126

**Comment by RhysJevons** [comment]
I've got the same issue, any update?

**Comment by lehresman** [comment]
It's not documented anywhere, but it looks like this library requires jQuery.  Without jQuery, Angular will use its own light emulation of jQuery, which apparently does not have the necessary drag/drop capabilities for this library.

**Comment by xinz** [comment]
I got the same issue, and find that you need to include the required jquery-ui library will resolve this issue, hope it would be helpful for you.

**Comment by codef0rmer** [comment]
`angular-dragdrop` is just a wrapper for jQueryUI draggable/droppable plugins which depends on jQuery.
